import { auth, signIn, signOut } from "@aspen/next-auth-public";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import "./globals.css";

const inter = Inter( { subsets: ["latin"] } );

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout( { children } ) {
    const session = await auth();

    console.log( `>>>>>>>>>>> Session >>>>>>>>>>>` );
    console.log( session );

    return (
        <html lang="en">
            <body className={`${inter.className} p-6`}>
                <section>
                    <h1 className={"text-xl"}>Auth Example</h1>
                    <div className={"mt-6"}>
                        {
                            session?.user &&
                            <SignOut>{`Welcome ${session?.user?.name}`}</SignOut>
                        }
                    </div>
                    <p className={"mt-6"}>{session?.accessToken}</p>
                </section>

                {children}
            </body>
        </html>
    );
}

function SignOut( { children } ) {
    return (
        <form
            action={async () => {
                "use server";
                await signOut();
            }}
        >
            <p className={"mb-6"}>{children}</p>
            <Button type="submit" variant={"outline"}>Sign out</Button>
        </form>
    );
}
