import { auth, signIn, signOut } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import Dashboard from "@/components/dashboard";
import "./globals.css";

const inter = Inter( { subsets: ["latin"] } );

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout( { children } ) {
    const session = await auth();
    
    return (
        <html lang="en">
            <body className={`${inter.className} p-6`}>
                <section>
                    <h1 className={"text-xl"}>Auth Example</h1>
                    <div className={"mt-6"}>
                        {
                            session?.user &&
                            <SessionProvider>
                                <Dashboard/>
                                <SignOut/>
                            </SessionProvider>
                        }
                    </div>
                    <p className={"mt-6"}>{session?.accessToken}</p>
                </section>

                {children}
            </body>
        </html>
    );
}

function SignOut() {
    return (
        <form
            action={async () => {
                "use server";
                await signOut();
            }}
        >
            <Button type="submit" variant={"outline"}>Sign out</Button>
        </form>
    );
}