import { auth, signIn, signOut } from "@/auth";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter( { subsets: ["latin"] } );

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout( { children } ) {
    let session = await auth();
    let user = session?.user?.email;

    return (
        <html lang="en">
            <body className={inter.className}>
                <section>
                    <h1>Home</h1>
                    <div>{user ? <SignOut>{`Welcome ${user}`}</SignOut> : <SignIn/>}</div>
                </section>
                
                {children}
            </body>
        </html>
    );
}

function SignIn() {
    return (
        <>
            <form
                action={async () => {
                    "use server";
                    await signIn( "google" );
                }}
            >
                <p>You are not logged in</p>
                <button type="submit">Sign in with Google</button>
            </form>

            <form
                action={async () => {
                    "use server";
                    await signIn( "facebook" );
                }}
            >
                <p>You are not logged in</p>
                <button type="submit">Sign in with Facebook</button>
            </form>
        </>
    );
}

function SignOut( { children } ) {
    return (
        <form
            action={async () => {
                "use server";
                await signOut();
            }}
        >
            <p>{children}</p>
            <button type="submit">Sign out</button>
        </form>
    );
}
